### ISSUE TITLE
Redesign implementation

### ISSUE THREAD

**Issue by m3ggle** [m3ggle/personal-portfolio#14]
You can find the redesign in Figma under „new …“

# Todos
## Figma
- [x] export the button background gradient as png +++ compress it 
## Sanity 
- [x] for the cta section insert all the different text variation
- [x] Cut out random meal for showcases
- [x] change the amount of viewable technologies (in order: Figma, GitHub, Tailwind, JavaScript, React, PostgreSQL)
- [x] change the schema of the footer part to only accompany „footer title“
- [x] Insert the title 
### Navbar
- [x] delete the old one 
- [x] Insert the new content (Name, Dev, Contact, Menu)
- [x] Make sure the text size is base
### Hero
- [x] The complete hero size is the size of the device, meaning h-screen
- [x] Everything what is included in the hero content should be viewable at first glance without scroll
### Layout
- [x] insert the scroll indication on the left and email on the right, make sure that everything under 600 the both are hidden
- [x] Insert the copyright
- [x] Create noise in the background, the issue #13 may help
### Button
- [x] Update the button design 
### Technologies 
- [x] update the title
- [x] Update the list of tech (UI)
   - you may want to use grid instead of flex for the correct responsive behaviour 
### Showcase(-s)
- [x] delete showcase of project 2, meaning only one project is going to be showcased on the homepage (Megg’s rental)
### CTA Section
- [x] implement the new design (only UI, animation later) without the background pattern
- [x] Try to implement the background pattern only for desktop version (greater than 1000)
- [x] Implement the redial gradient 
### Footer 
- [x] the old design is obsolete
- [x] implement the new design with „back to the top“ part (in a different component)
